name: C++ CI

on: [push, pull_request]  # يُنفَّذ عند push أو pull request

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # أو windows-latest / macos-latest

    steps:
      - uses: actions/checkout@v4  # تحميل الكود

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake ..

      - name: Build
        working-directory: ./build
        run: cmake --build .

      - name: Run tests
        working-directory: ./build
        run: ctest  # إذا كنت تستخدم CMake مع اختبارات (اختياري)
