name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make

      - name: Verify project structure
        run: |
          echo "محتويات المشروع:"
          ls -la
          echo "محتويات ملف CMakeLists.txt:"
          cat CMakeLists.txt

      - name: Fake build & test
        run: |
          echo "هذا اختبار وهمي للبناء"
          echo "لو كان هناك كود حقيقي لتم بناؤه هنا"
          exit 0