name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake ..

      - name: Build
        working-directory: ./build
        run: cmake --build .

      - name: Fake test (always passes)
        run: echo "This is a fake test - always passes" && exit 0